client:
  registration:
    name: runTheBank

server:
  port: 8081
  servlet:
    context-path: /run-the-bank
  max-http-request-header-size: 16KB

spring:
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
    default-property-inclusion: NON_NULL
  datasource:
    url: jdbc:h2:mem:testdb
    username: runthebank
    password: runthebank
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update